version: '3'

services:
  mydb:
    image: mysql:5.7
    volumes: 
      - db_storage:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: vvp
      MYSQL_PASSWORD: vvp
      MYSQL_DATABASE: vvp_db
      
      
    
    
